name: what2see
description: A sample Polymer application
dependencies:
    polymer: ">=0.12.0 <0.13.0"
    core_elements: ">=0.2.0 <0.3.0"
    paper_elements: ">=0.1.0 <0.2.0"
    csvparser: ">=1.0.8 <2.0.0"  
transformers:
- polymer:
    entry_points: web/what2see.html
